# Generated by Django 5.2.16 on 2026-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_status_22f3a0_idx',
            old_name='imports_batch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_created_f50fe3_idx',
            old_name='imports_batch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='importrow',
            new_name='imports_imp_import__6e0414_idx',
            old_name='imports_row_batch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='importrow',
            new_name='imports_imp_cin_51d0eb_idx',
            old_name='imports_row_cin_idx',
        ),
        migrations.RenameIndex(
            model_name='importrow',
            new_name='imports_imp_process_c376c7_idx',
            old_name='imports_row_stage_idx',
        ),
    ]
