# Generated by Django 5.2.16 on 2026-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_widen_benefit_decimal_fields'),
        ('patients', '0002_change_history_conflict'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_cin_b86cc5_idx',
            old_name='patients_pa_cin_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(db_index=True, help_text='Medicaid Client Identification Number', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='patientchangehistory',
            index=models.Index(fields=['patient', 'field_name'], name='patients_pa_patient_17fe8a_idx'),
        ),
    ]
