from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(db_index=True, max_length=20)),
                ('date_of_service', models.DateField(db_index=True)),
                ('service_type_code', models.CharField(default='30', max_length=10)),
                ('request_status', models.CharField(choices=[('PENDING','Pending'),('SUBMITTED','Submitted'),('FAILED','Failed')], default='PENDING', max_length=20)),
                ('request_control_number', models.CharField(blank=True, max_length=50)),
                ('isa_control_number', models.CharField(blank=True, max_length=20)),
                ('gs_control_number', models.CharField(blank=True, max_length=20)),
                ('st_control_number', models.CharField(blank=True, max_length=20)),
                ('payload_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_270', models.TextField(blank=True)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('content_length', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_request', to='imports.importrow')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_requests', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('X12_271','X12 271'),('TA1','TA1 Acknowledgement'),('X12_999','X12 999'),('CORE_ERROR','CORE Error'),('HTTP_ERROR','HTTP Error'),('UNKNOWN','Unknown')], default='UNKNOWN', max_length=20)),
                ('response_status', models.CharField(choices=[('SUCCESS','Success'),('ELIGIBLE','Eligible'),('INELIGIBLE','Ineligible'),('REJECTED','Rejected'),('MEMBER_NOT_FOUND','Member Not Found'),('TECHNICAL_FAILURE','Technical Failure'),('UNKNOWN','Unknown')], default='UNKNOWN', max_length=30)),
                ('eligibility_status', models.CharField(blank=True, max_length=200)),
                ('member_found', models.BooleanField(default=False)),
                ('coverage_start_date', models.DateField(blank=True, null=True)),
                ('coverage_end_date', models.DateField(blank=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('plan_identifier', models.CharField(blank=True, max_length=100)),
                ('managed_care_name', models.CharField(blank=True, max_length=200)),
                ('response_control_number', models.CharField(blank=True, max_length=50)),
                ('raw_271', models.TextField(blank=True)),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('content_length', models.IntegerField(default=0)),
                ('parser_version', models.CharField(default='1.0', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('is_final_response', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='eligibility.eligibilityrequest')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_responses', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientEligibilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField(db_index=True)),
                ('is_medicaid_eligible', models.BooleanField(default=False)),
                ('has_recertification', models.BooleanField(db_index=True, default=False)),
                ('recertification_date', models.DateField(blank=True, db_index=True, null=True)),
                ('has_nhtd', models.BooleanField(db_index=True, default=False)),
                ('has_code_60', models.BooleanField(db_index=True, default=False)),
                ('has_surplus', models.BooleanField(db_index=True, default=False)),
                ('surplus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='eligibility.eligibilityresponse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_snapshots', to='patients.patient')),
            ],
            options={'ordering': ['-date_of_service', '-created_at']},
        ),
        migrations.CreateModel(
            name='EligibilityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('RECERTIFICATION','Recertification'),('NHTD','NHTD'),('WAIVER_PROGRAM','Waiver Program'),('COVERAGE_CODE','Coverage Code'),('CODE_60','Code 60'),('SURPLUS','Surplus'),('OTHER','Other')], db_index=True, max_length=30)),
                ('indicator_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('indicator_value', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_segment', models.CharField(blank=True, max_length=20)),
                ('source_element', models.CharField(blank=True, max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='eligibility.eligibilityresponse')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityFinancialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_type', models.CharField(choices=[('SURPLUS','Surplus'),('SPEND_DOWN','Spend Down'),('COPAY','Co-pay'),('DEDUCTIBLE','Deductible'),('COINSURANCE','Co-insurance'),('OTHER','Other')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_type', models.CharField(blank=True, max_length=50)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('source_segment', models.CharField(blank=True, max_length=20)),
                ('source_element', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_details', to='eligibility.eligibilityresponse')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_details', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_code', models.CharField(blank=True, max_length=10)),
                ('service_type_description', models.CharField(blank=True, max_length=200)),
                ('benefit_information_code', models.CharField(blank=True, max_length=10)),
                ('coverage_level_code', models.CharField(blank=True, max_length=10)),
                ('insurance_type_code', models.CharField(blank=True, max_length=10)),
                ('plan_coverage_description', models.CharField(blank=True, max_length=200)),
                ('time_period_qualifier', models.CharField(blank=True, max_length=10)),
                ('monetary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('network_indicator', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('source_segment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='eligibility.eligibilityresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject_code', models.CharField(blank=True, max_length=20)),
                ('follow_up_action_code', models.CharField(blank=True, max_length=20)),
                ('entity_identifier_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('segment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligibility_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='eligibility.eligibilityresponse')),
            ],
        ),
    ]
