# Generated by Django 5.2.16 on 2026-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
        ('imports', '0002_widen_benefit_decimal_fields'),
        ('patients', '0002_change_history_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitybenefit',
            name='monetary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitybenefit',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='eligibilityfinancialdetail',
            index=models.Index(fields=['financial_type', 'amount'], name='eligibility_financi_e19aae_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityindicator',
            index=models.Index(fields=['indicator_type', 'is_active'], name='eligibility_indicat_10af78_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityindicator',
            index=models.Index(fields=['indicator_code'], name='eligibility_indicat_fc2d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityrequest',
            index=models.Index(fields=['cin'], name='eligibility_cin_e0e6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityrequest',
            index=models.Index(fields=['cin', 'date_of_service'], name='eligibility_cin_2f9041_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityrequest',
            index=models.Index(fields=['payload_id'], name='eligibility_payload_3372cb_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityresponse',
            index=models.Index(fields=['patient', 'response_status'], name='eligibility_patient_c67eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityresponse',
            index=models.Index(fields=['received_at'], name='eligibility_receive_f30725_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['patient', 'date_of_service'], name='eligibility_patient_0bcc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['patient', 'is_current'], name='eligibility_patient_42d9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_recertification', 'recertification_date'], name='eligibility_has_rec_cf87af_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_nhtd'], name='eligibility_has_nht_bb28c3_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_code_60'], name='eligibility_has_cod_4f4971_idx'),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_surplus'], name='eligibility_has_sur_05e9e5_idx'),
        ),
    ]
