# Generated by Django 5.2.16 on 2026-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_widen_benefit_decimal_fields'),
        ('patients', '0003_widen_benefit_decimal_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patienteligibilitysnapshot',
            name='eligibility_has_rec_cf87af_idx',
        ),
        migrations.RemoveIndex(
            model_name='patienteligibilitysnapshot',
            name='eligibility_has_nht_bb28c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='patienteligibilitysnapshot',
            name='eligibility_has_sur_05e9e5_idx',
        ),
        migrations.RemoveField(
            model_name='patienteligibilitysnapshot',
            name='has_nhtd',
        ),
        migrations.RemoveField(
            model_name='patienteligibilitysnapshot',
            name='has_recertification',
        ),
        migrations.RemoveField(
            model_name='patienteligibilitysnapshot',
            name='has_surplus',
        ),
        migrations.RemoveField(
            model_name='patienteligibilitysnapshot',
            name='recertification_date',
        ),
        migrations.RemoveField(
            model_name='patienteligibilitysnapshot',
            name='surplus_amount',
        ),
        migrations.AddField(
            model_name='patienteligibilitysnapshot',
            name='has_s1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='eligibilityindicator',
            name='indicator_type',
            field=models.CharField(choices=[('CODE_60', 'Code 60'), ('S1', 'S1'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_s1'], name='eligibility_has_s1_6a8a4a_idx'),
        ),
    ]
