# Generated by Django 5.2.16 on 2026-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0003_remove_patienteligibilitysnapshot_eligibility_has_rec_cf87af_idx_and_more'),
        ('patients', '0003_widen_benefit_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienteligibilitysnapshot',
            name='has_recertification',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='patienteligibilitysnapshot',
            name='recertification_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityindicator',
            name='indicator_type',
            field=models.CharField(choices=[('RECERTIFICATION', 'Recertification'), ('CODE_60', 'Code 60'), ('S1', 'S1'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='patienteligibilitysnapshot',
            index=models.Index(fields=['has_recertification', 'recertification_date'], name='eligibility_has_rec_cf87af_idx'),
        ),
    ]
